In [2]:
import pandas as pd

df=pd.read_excel("IPL.xls")

In [7]:
matchs=df[(df["Bat_Second_15_ov_wkts_lost"]==6)&(df["Bat_Second_20_ov_score"]-df["Bat_Second_15_ov_score"]==33)&(df["Winning_Team"]=="FirstBatting")]
matchs[['Match_Number','Date','Team_Batting_First','Team_Batting_Second']]

     Match_Number    Date Team_Batting_First Team_Batting_Second
301           302  May 11          Bangalore                Pune

In [9]:
matches_2 = df[(df["Bat_First_15_ov_wkts_lost"]==2)&(df["Bat_First_20_ov_score"]-df["Bat_First_15_ov_score"]<25)]
matches_2[['Match_Number','Date','Team_Batting_First','Team_Batting_Second']]

     Match_Number    Date Team_Batting_First Team_Batting_Second
100           101  May 14          Rajasthan              Mumbai